In [13]:
import numpy as np

In [2]:
array_values = [1, 2, 3, 4, 5]

In [3]:
array_values

[1, 2, 3, 4, 5]

In [20]:
# using array() method
number_array = np.array((1, 2, 3, 4))

In [27]:
number_array

array([1, 2, 3, 4])

In [21]:
print(number_array)

[1 2 3 4]


In [23]:
# Zero dimension

In [24]:
zero = np.array(90)

In [28]:
zero

array(90)

In [26]:
print(zero)

90


In [29]:
# One dimension

In [31]:
one = np.array([1, 2, 3, 4, 5])

In [32]:
one

array([1, 2, 3, 4, 5])

In [33]:
# Two Dimension

In [44]:
two = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)])

In [45]:
two

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
# Three Dimension

In [51]:
three = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[2, 4, 6], [8, 10, 12], [14, 16, 18]]])

In [52]:
three

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [63]:
# find the dimension using ndim

In [11]:
zero = np.array(233)
one = np.array([1, 2, 3, 4])
two = np.array([[1, 3, 5, 7], [9, 11, 13, 15]])
three = np.array([[[2, 4, 6], [8, 10, 12]], [[14, 16, 18], [20, 22, 24]]])

In [12]:
three.shape

(2, 2, 3)

In [65]:
zero.ndim

0

In [66]:
one.ndim

1

In [67]:
two.ndim

2

In [68]:
three.ndim

3

In [69]:
# Array Indexing

In [76]:
first = np.array(["shiva", 1, 2, 3, 5, "16"])

In [77]:
first[0]

np.str_('shiva')

In [78]:
print(first[0])

shiva


In [79]:
first[0] + first[len(first) - 1]

'shiva16'

In [80]:
# Indexing in 2d
two = np.array([[1, 3, 5, 7], [9, 11, 13, 15]])

In [86]:
two[0,2] + two[1,3]

np.int64(20)

In [87]:
# Indexing in 3d

In [88]:
three = np.array([[[2, 4, 6], [8, 10, 12]], [[14, 16, 18], [20, 22, 24]]])

In [90]:
(three[0, 0, 1] + three[0, 1, 1]) + (three[1, 0, 1] + three[1, 1, 1])

np.int64(52)

In [91]:
# Slicing array

In [92]:
first = np.array(["shiva", 1, 2, 3, 5, "16"])

In [95]:
print(first[-3:-1])

['3' '5']


In [96]:
two = np.array([[1, 3, 5, 7], [9, 11, 13, 15]])

In [102]:
print(two[0, 1:4])

[3 5 7]


In [103]:
print(two[1:4, 1])

[11]


In [105]:
print(two[1::, ::-1])

[[15 13 11  9]]


In [106]:
print(two[1, 1:4])

[11 13 15]


In [110]:
print(two[::-1, 0:2])

[[ 9 11]
 [ 1  3]]


In [111]:
# Data type conversion

In [138]:
Data_value = np.array([[1.0, 3, 5, 7],
               [2, 4, 6, 8]])

In [139]:
new_type = Data_value.astype('i8')

In [141]:
new_type

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [142]:
# copy and view

In [143]:
array_value = np.array([1, 2, 3, 4, 5])

In [144]:
new_array = np.copy(array_value)

In [147]:
new_array[0] = 23

In [148]:
new_array

array([23,  2,  3,  4,  5])

In [149]:
array_value

array([1, 2, 3, 4, 5])

In [150]:
# view

In [151]:
array_value = np.array([1, 2, 3, 4, 5])

In [152]:
new = array_value.copy()

In [154]:
new_1 = array_value.view()

In [155]:
new

array([1, 2, 3, 4, 5])

In [156]:
new_1

array([1, 2, 3, 4, 5])

In [157]:
new.base

In [158]:
new_1.base

array([1, 2, 3, 4, 5])

In [159]:
# Shape

In [165]:
three = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[2, 4, 6], [8, 10, 12], [14, 16, 18]]], ndmin = 5)

In [167]:
three

array([[[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[ 2,  4,  6],
          [ 8, 10, 12],
          [14, 16, 18]]]]])

In [168]:
three.shape

(1, 1, 2, 3, 3)

In [169]:
# Reshape

In [170]:
three = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[2, 4, 6], [8, 10, 12], [14, 16, 18]]])

In [7]:
three.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [173]:
three.reshape(3, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9,  2,  4,  6],
       [ 8, 10, 12, 14, 16, 18]])

In [174]:
three.reshape(3, 6).base

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [175]:
# unknown Dimension

In [185]:
one = np.array([1, 3, 5, 31, 4, 2])

In [186]:
one.reshape(-1, 2)

array([[ 1,  3],
       [ 5, 31],
       [ 4,  2]])

In [3]:
three = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[2, 4, 6], [8, 10, 12], [14, 16, 18]]])

In [4]:
three.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  2,  4,  6,  8, 10, 12, 14, 16,
       18])

In [5]:
# Iterating the Array

In [19]:
iterate_values = np.array([[[1, 2, 3], [4, 5, 6]],[[12, 13, 14], [15, 16, 17]]])

In [20]:
for value in iterate_values:
    print(value)

[[1 2 3]
 [4 5 6]]
[[12 13 14]
 [15 16 17]]


In [22]:
for value in iterate_values:
    for value_1 in value:
        for value_2 in value_1:
            print(value_2)

1
2
3
4
5
6
12
13
14
15
16
17


In [23]:
# Iterating array with different data types

In [24]:
iterate_values = np.array([[[1, 2, 3], [4, 5, 6]],[[12, 13, 14], [15, 16, 17]]])

In [33]:
for value in np.nditer(iterate_values, flags = ['buffered'], op_dtypes = 'S'):
    print(value)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'12')
np.bytes_(b'13')
np.bytes_(b'14')
np.bytes_(b'15')
np.bytes_(b'16')
np.bytes_(b'17')


In [34]:
# Iterating array with different step size

In [35]:
iterate_values = np.array([[[1, 2, 3], [4, 5, 6]],[[12, 13, 14], [15, 16, 17]]])

In [49]:
for value in np.nditer(iterate_values[0::, 0]):
    print(value)

1
2
3
12
13
14


In [50]:
# enumerate Iteration

In [51]:
iterate_values = np.array([[[1, 2, 3], [4, 5, 6]],[[12, 13, 14], [15, 16, 17]]])

In [53]:
for id, value in np.ndenumerate(iterate_values):
    print(id,value)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 12
(1, 0, 1) 13
(1, 0, 2) 14
(1, 1, 0) 15
(1, 1, 1) 16
(1, 1, 2) 17


In [54]:
# Joining Arrays using concatenate()

In [72]:
array_1 = np.array([["Sankar", "Kiruba", "Bala"], ["Shiva", "Sam", "Deva"]])

In [79]:
array_2 = np.array([["Prabhu", "Ajay", "Shri"], ["Sona", "Sathya", "Radha"]])

In [80]:
join = np.concatenate((array_1, array_2), axis = 1)

In [82]:
join

array([['Sankar', 'Kiruba', 'Bala', 'Prabhu', 'Ajay', 'Shri'],
       ['Shiva', 'Sam', 'Deva', 'Sona', 'Sathya', 'Radha']], dtype='<U6')

In [84]:
# joining using Stacking (without any axis 1D Arrays)

In [89]:
array_1 = np.array(["Sankar", "Kiruba", "Bala"])

In [90]:
array_2 = np.array(["Sona", "Sathya", "Radha"])

In [91]:
add_stack = np.stack((array_1, array_2), axis = 1)

In [92]:
add_stack

array([['Sankar', 'Sona'],
       ['Kiruba', 'Sathya'],
       ['Bala', 'Radha']], dtype='<U6')

In [93]:
# hstack, vstack, dstack

In [94]:
array_2 = np.array([["Prabhu", "Ajay", "Shri"], ["Sona", "Sathya", "Radha"]])

In [99]:
values = np.vstack(array_2)

In [100]:
values

array([['Prabhu', 'Ajay', 'Shri'],
       ['Sona', 'Sathya', 'Radha']], dtype='<U6')

In [102]:
np.hstack(values)

array(['Prabhu', 'Ajay', 'Shri', 'Sona', 'Sathya', 'Radha'], dtype='<U6')

In [103]:
np.dstack(values)

array([[['Prabhu', 'Sona'],
        ['Ajay', 'Sathya'],
        ['Shri', 'Radha']]], dtype='<U6')

In [104]:
# Splitting Array

In [143]:
array_2 = np.array([["Prabhu", "Ajay"], ["Shri", "Sona"], ["Sathya", "Radha"]])

In [146]:
new_split = np.array_split(array_2, 7, axis = 1)

In [147]:
new_split

[array([['Prabhu'],
        ['Shri'],
        ['Sathya']], dtype='<U6'),
 array([['Ajay'],
        ['Sona'],
        ['Radha']], dtype='<U6'),
 array([], shape=(3, 0), dtype='<U6'),
 array([], shape=(3, 0), dtype='<U6'),
 array([], shape=(3, 0), dtype='<U6'),
 array([], shape=(3, 0), dtype='<U6'),
 array([], shape=(3, 0), dtype='<U6')]

In [154]:
# hsplit, vsplit, dsplit

In [155]:
array_2 = np.array([["Prabhu", "Ajay"], ["Shri", "Sona"], ["Sathya", "Radha"]])

In [166]:
np.vsplit(array_2, 1)

[array([['Prabhu', 'Ajay'],
        ['Shri', 'Sona'],
        ['Sathya', 'Radha']], dtype='<U6')]

In [167]:
# Searching Array

In [168]:
array_2 = np.array([["Prabhu", "Ajay"], ["Shri", "Sona"], ["Sathya", "Radha"]])

In [171]:
np.where(array_2 == "Shri")

(array([1]), array([0]))

In [172]:
number_array = np.array(list(range(0,11)))

In [173]:
number_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
np.where(number_array % 2 == 0)

(array([ 0,  2,  4,  6,  8, 10]),)

In [175]:
# Searchsorted()

In [180]:
number_array = np.array([1, 4, 5, 6, 8])

In [190]:
search = np.searchsorted(number_array, 1, side = "right")

In [191]:
search

np.int64(1)

In [192]:
search_1 = np.searchsorted(number_array, [2, 3])

In [193]:
search_1

array([1, 1])

In [39]:
array_1 = np.array([11, 3, 5, 16, 8, 12, 2])  

In [50]:
value = np.searchsorted(array_1, [0, 1, 10, 4], side = "right") # [16, 12, 11, 8, 5, 3, 2] 

In [51]:
print(value)

[0 0 3 2]
